//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectPetey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id_L { get; set; }
        public string Distance { get; set; }
        public string Distance2 { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<int> ID_Pet { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> ID_Trainer { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual Product Product { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
