//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectPetey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orders_Details = new HashSet<Orders_Details>();
        }
    
        public int Order_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<decimal> Grand_total { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<System.DateTime> Ship_date { get; set; }
        public string Order_status { get; set; }
        public string Card_No { get; set; }
        public string Card_Name { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Details> Orders_Details { get; set; }
    }
}
