//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectPetey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Details
    {
        public int Order_Details_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Product_Id2 { get; set; }
        public Nullable<int> Product_Id3 { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Sub_total { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
