//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectPetey.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectPeteyEntities : DbContext
    {
        public ProjectPeteyEntities()
            : base("name=ProjectPeteyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Orders_Details> Orders_Details { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<PeviewStar> PeviewStars { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SumCargo> SumCargoes { get; set; }
        public virtual DbSet<Top> Tops { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
    }
}
