//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectPetey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top
    {
        public int Top_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Product_id2 { get; set; }
        public Nullable<int> Product_id3 { get; set; }
        public Nullable<int> Counts { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Product Product { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
